global:
  scrape_interval: 5s

scrape_configs:
  - job_name: marketpulse-api
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:5082"]
  - job_name: marketpulse-workers
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:9465"]
